repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: end-of-file-fixer
    name: fix eofs
  - id: mixed-line-ending
    name: fix line endings
  - id: trailing-whitespace
    name: remove trailing whitespace

- repo: local
  hooks:
  - id: resume
    name: generate resume pdfs
    language: system
    always_run: true
    pass_filenames: false
    entry: sh -c "cd _resume && ./make.sh"
