sudo: required
dist: trusty

language: ruby
rvm:
  - "2.4"

before_install:
  - gem install bundler
  - wget https://github.com/jgm/pandoc/releases/download/2.1.2/pandoc-2.1.2-1-amd64.deb
  - sudo dpkg -i pandoc-2.1.2-1-amd64.deb

install:
  - bundle install

script:
  - bundle exec jekyll build

branches:
  only:
    - source

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source
  target-branch: master
