name: Deploy website

on:
  workflow_dispatch:
  push:
    branches:
    - source

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jayanthkoushik/paje@v3
      with:
        setupscript: |
            cp CNAME /www
            cp robots.txt /www
            cp index.md /www
            cp -r pdfs /www
            cp -r _data /www
            cp _includes/* /www/_includes/
        targetbranch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
